services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gestao_materiais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gtadmin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist DB data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: gtadmin@domain.com
      PGADMIN_DEFAULT_PASSWORD: gtroot
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: ./backend
    command: bash -c "chmod +x backend.sh && ./backend.sh"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:gtadmin@db:5432/gestao_materiais
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid host-node_modules conflict
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - REACT_APP_API_URL=http://backend:8000  # Use service name for API calls
    stdin_open: true  # Enable hot-reload
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:  # Persistent volume for PostgreSQL